esphome:
  name: nightlight
  platform: ESP8266
  board: d1_mini

#  on_boot:
#    priority: 600
#    then:
#      - light.turn_on:
#          id: night_light
#          brightness: 100%
#          red: 100%
#          green: 67%
#          blue: 0%
#      - delay: 60s
#      - light.turn_off:
#          id: night_light

logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: !secret HassApiEncryptionKey

ota:
  platform: esphome
  password: !secret OtaPassword

wifi:
  networks:
    - ssid: !secret WifiSSID1
      password: !secret WifiPassword
    - ssid: !secret WifiSSID2
      password: !secret WifiPassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BmeTransmitter Fallback Hotspot"
    password: !secret FallBackHotspotPassword

captive_portal:
web_server:
  port: 80


light:
  - platform: neopixelbus
    id: night_light
    type: grb
    pin: D3
    num_leds: 18
    name: "Night Light"
    variant: ws2812

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode:
        input: true
    name: "Floor motion detector"
    device_class: motion
    # filters:
    #  - delayed_on: 500ms
    #  - delayed_off: 5000ms
    # on_press:
    #     - light.turn_on:
    #         id: night_light
    #         brightness: 100%
    #         red: 100%
    #         green: 67%
    #         blue: 0%
    #         transition_length: 1s
    # on_release:
    #     - light.turn_off:
    #         id: night_light
    #         transition_length: 3s

sensor:
  - platform: adc
    pin: A0
    name: "LUX Sensor"
    update_interval: '3s'
    unit_of_measurement: lux
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;

